### ISSUE TITLE
Using WebDriver

### ISSUE THREAD

**Issue by paezagon** [immersive-web/webxr-test-api#1]
This is a continuation of the discussion from https://github.com/immersive-web/proposals/issues/8, about whether it would be better to specify a WebDriver API or a Javascript API. 

To reiterate: What are the advantages of using WebDriver directly as opposed to using an API that could be backed by WebDriver?

**Comment by ryzngard** [comment]
After discussing with @RafaelCintron and @SamiraAtMicrosoft we think that WebDriver doesn't add value to the goal of this API set. WebDriver would add value if this were more similar to a driver or runtime backed simulated device; I believe the target here is geared towards mocking out device parameters rather than emulating a certain type of device. 

We're still reviewing the APIs, but moving forward and iterating on what is presented seems to be the best path.

**Comment by ryzngard** [comment]
We can probably close this issue now.

**Comment by paezagon** [comment]
I'd like to get some more feedback before we consider it closed.

**Comment by alcooper91** [comment]
Given that there was no further discussion on this, and we're kind of resetting (with a Javascript API still), as of #10  I'm going to close this issue out.  Please re-open if you feel it should be re-discussed.
