### ISSUE TITLE
Provide a way to test updateRenderState() with clip planes

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr-test-api#39]
When you call `updateRenderState({ near: ..., far: ...})` the implementation is supposed to calculate new projection matrix values using the new clip plane values.

Given that we always supply the projection matrix directly there is no way to test this API.

Perhaps we should have an FOV setter in ViewInit instead of the projection matrix array?

**Comment by alcooper91** [comment]
Given that the test api is simulating a device, I think it's possible for this to be done by the UA without passing data back to the device.  We currently have:
https://github.com/web-platform-tests/wpt/blob/master/webxr/xrView_oneframeupdate.https.html
Which validates that a different projection matrix gets returned after calling `updateRenderState({ near: ..., far...})`

**Comment by Manishearth** [comment]
How can the test device calculate the new projection matrix without FOV values, though? That test seems broken -- what is Chrome doing to create a new projection matrix?

The problem here is that the test API allows you to set the projection matrix as a whole, and the webxr API allows you to set depth values which are an ingredient of the projection matrix. When you change depth values there's no clear way to also change projection matrix values since you have no FOV to recalculate from.

**Comment by alcooper91** [comment]
Chrome currently sends up the FOVs from the device side and converts it to the projection matrix on the blink side, thus taking the depth values into account there.  Though I believe at least one runtime does decompose the projection matrix into those FOV values. I can send you pointers to some bits of code if you want (webxr-test.js has getEye which decomposes the passed in matrix for the tests).

**Comment by Manishearth** [comment]
> Chrome currently sends up the FOVs from the device side and converts it to the projection matrix on the blink side, thus taking the depth values into account there

Right, but for the test API you don't _have_ FOV values, you only have a projection matrix. Is the test API backend using decomposition?

I'd rather not _require_ matrix decomposition as a part of the test API.

**Comment by alcooper91** [comment]
That is indeed what our test API is doing as a side effect of our implementation.

Changing to an FOV Setter would almost certainly be a breaking change, especially since the projection matrix is a required attribute for FakeXRViewInit which are themselves required as part of the FakeXRDeviceInit.

I think that there are two equally valid ways for UAs to support these clip planes, and it's largely based on what API the runtimes give them.
Either:
1) Manually apply the clip plane to the FOV values
2) Plumb the passed in clip plane values to the runtime

Even in the case where the API supplies two as an option, UAs still have the option of (at least trying to) decompose the matrix to do 1, and thus consolidate their implementation.

**Comment by Manishearth** [comment]
> Changing to an FOV Setter would almost certainly be a breaking change

Yep, but I think it's necessary enough and we can coordinate it now since we're the only two implementors. The current API doesn't make sense.

> Plumb the passed in clip plane values to the runtime

In this case the runtime is still doing the computation of the projection matrices. _Someone_ is computing the projection matrix from the clip plane and FOV, the value derives from both.

**Comment by alcooper91** [comment]
> > Changing to an FOV Setter would almost certainly be a breaking change
> 
> Yep, but I think it's necessary enough and we can coordinate it now since we're the only two implementors. The current API doesn't make sense.

TBH, it's quite a large breaking change that I'm not sure of when we'd have the bandwidth to implement.  I have a proposed compromise though.  See below.
> 
> > Plumb the passed in clip plane values to the runtime
> 
> In this case the runtime is still doing the computation of the projection matrices. _Someone_ is computing the projection matrix from the clip plane and FOV, the value derives from both.
Right, I was originally thinking that this would mean we would need to do some form of "enforce that a call to 'setClipPlanes' happened", but I think that can be ignored as an implementation detail of an internal interface that the different UAs use.

I was typing up this follow up thought/potential path forward when you replied:
I suppose since a projection matrix is composable from the FOVs, it should be possible to have an option to set one or the other, with a requirement that exactly one of the two fields must be set (Not sure if the idl provides a way to enforce this), and that likely wouldn't be a breaking change.  We could then argue that setting the projection matrix is not suitable for tests of updateRenderState (given that while some UAs may decompose them as a matter of course, not all may), and then whether or not UAs internally mimic a device that they set the clip planes on and it gives the updated projection matrix or if they re-compose the FOV with the supplied clip planes outside of the test process is an internal implementation detail.

**Comment by Manishearth** [comment]
> it should be possible to have an option to set one or the other

Not exactly, because only one of these lets you mix clip plane information into projection matrices.

>  We could then argue that setting the projection matrix is not suitable for tests of updateRenderState (given that while some UAs may decompose them as a matter of course, not all may),

This would be fine.

I'm okay with having an optional FOV argument in FakeXRDeviceInit for this, as long as we document this behavior.

We can then slowly migrate all tests to using this, at our leisure, and eventually get rid of the projectionMatrix argument if no tests are using it.

**Comment by alcooper91** [comment]
Given that the spec explicitly states that projection matrices may contain shear or other things, I don’t know that we can ever fully remove the projectionMatrix argument as we may want to write some tests around scenarios with that:
https://immersive-web.github.io/webxr/#view-projection-matrix

**Comment by Manishearth** [comment]
Hmm. that's unfortunate, but i guess that's fine. We should mandate that implementations ignore the projection matrix when FOV is set, and we can later change the API so that either one or the other is required.
