### ISSUE TITLE
FakeXRSessionController

### ISSUE THREAD

**Issue by paezagon** [immersive-web/webxr-test-api#8]
Would it make sense to add fake session objects and controllers?

Some functions might make more sense to be on a session-related controller object rather than on the device controller. For example:
```
void simulateForcedEndSession(XRSession);
void simulateBlurSession(XRSession);
Void simulateFocusSession(XRSession);
```
And in future, if we have any other functions that are session specific, it would be good to have a controller to attach them to. 

One issue with this is how we get the controller. It does not make sense to have an AddSession function that returns the controller like we have for device, as the XRSessions are created by the actual XRDevice object. Therefore we’d need to have some kind of `GetSessionController(XRSession)` function, which is a bit awkward.

**Comment by ryzngard** [comment]
I'm not sure I like the idea of adding a session controller. Sessions are very much a code construction, and not directly related to any user action (aside from pressing UI buttons I guess). I like that the device controller currently handles these actions, as it simulates a device being used in a certain way rather than directly manipulating the end result.

**Comment by alcooper91** [comment]
Given that there's been no discussion on this for over a year, I'm going to close this out.  Please re-open or file a new issue if you feel it should be re-addressed

I tend to agree, that it's nice to be able to write the tests directly as manipulating an underlying device.  Controllers are now created independently and then attached to the device or disconnected/re-connected by themselves.
